// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrEaVRZQos6gf3dhs6f4DZAORHkTDqvk',
    appId: '1:575904813553:web:e3b3e1a507e68ed9b37450',
    messagingSenderId: '575904813553',
    projectId: 'pillura-med',
    authDomain: 'pillura-med.firebaseapp.com',
    storageBucket: 'pillura-med.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1yGOWcF4KgI9vxwahiu40N73SIkS1yR8',
    appId: '1:575904813553:android:fbc27dfea9d601a2b37450',
    messagingSenderId: '575904813553',
    projectId: 'pillura-med',
    storageBucket: 'pillura-med.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67H1VsPGj-COo8z2tbc4WBsf2k1KZ8es',
    appId: '1:575904813553:ios:5942ca0bdf3907b9b37450',
    messagingSenderId: '575904813553',
    projectId: 'pillura-med',
    storageBucket: 'pillura-med.firebasestorage.app',
    iosBundleId: 'com.example.pilluraMed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67H1VsPGj-COo8z2tbc4WBsf2k1KZ8es',
    appId: '1:575904813553:ios:5942ca0bdf3907b9b37450',
    messagingSenderId: '575904813553',
    projectId: 'pillura-med',
    storageBucket: 'pillura-med.firebasestorage.app',
    iosBundleId: 'com.example.pilluraMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdrEaVRZQos6gf3dhs6f4DZAORHkTDqvk',
    appId: '1:575904813553:web:239d8de1af31fd5db37450',
    messagingSenderId: '575904813553',
    projectId: 'pillura-med',
    authDomain: 'pillura-med.firebaseapp.com',
    storageBucket: 'pillura-med.firebasestorage.app',
  );
}
